import React from "react";

interface ChatHeaderProps {
  model: string;
  prompt: string;
}

export const ChatHeader = ({ model, prompt }: ChatHeaderProps) => {
  return (
    <div className="mb-6">
      <h1 className="text-lg sm:text-xl md:text-2xl font-bold text-center mb-4">
        <span className="text-slate-600">Prompt:</span>{" "}
        <span className="text-sky-700">{prompt}</span>
      </h1>
      <h2 className="text-base sm:text-lg md:text-xl font-bold text-center">
        <span className="text-slate-600">Questions generated by </span>{" "}
        <span className="text-sky-600">{model}</span>
      </h2>
    </div>
  );
};
