import React from "react";

interface ChatHeaderProps {
  model: string;
  prompt: string;
}

export const ChatHeader = ({ model }: ChatHeaderProps) => {
  return (
    <div className="mb-6">
      <h2 className="text-base sm:text-lg md:text-xl font-bold text-center">
        <span className="text-slate-600">Questions generated by </span>{" "}
        <span className="text-sky-600">{model}</span>
      </h2>
    </div>
  );
};
