import { ChatHeaderProps } from "@/types/responsePage";

export const ChatHeader = ({ model }: ChatHeaderProps) => {
  return (
    <div className="mb-6 text-center space-y-2">
      <h2 className="text-base sm:text-lg md:text-xl font-bold">
        <span className="text-slate-600">Questions generated by </span>
        <span className="text-sky-600">{model ?? "—"}</span>
      </h2>

      {/* Disclaimer */}
      <p className="text-xs sm:text-sm text-slate-500 mx-auto max-w-3xl">
        ⚠️ Model outputs may contain inaccuracies. The generation is
        nondeterministic, and the number of produced questions may differ from
        the requested amount.
      </p>
    </div>
  );
};
